### ISSUE TITLE
Hard Crash during ACU Explosion

### ISSUE THREAD

**Issue by JJ173** [Nomads-Project/nomads#62] opened 2017-01-19 12:12 UTC
When I blew up my ACU, it spammed my console with a lot of errors and left some static models of engineers behind (nearby engineers). The engineers surrounded the ACU on explosion and they were destroyed but didn't disappear or leave a wreckage. I had no control over the unit and it had no icon, but it's model just sat there. After the first attempt of self-destructing the ACU, I did it again. It froze my game. Could be a major issue when two players are using Nomads.

**Comment by JJ173** [comment] 2017-01-19 12:21
[dev.txt](https://github.com/Nomads-Project/nomads/files/716541/dev.txt)

This happens when using instantly killing units instead of waiting the 5 seconds for a self-destruct using CTRL K.

**Comment by CookieNoob** [comment] 2017-01-19 13:17
same bug as #35

**Comment by TheKeyBlue** [comment] 2017-01-19 13:35
you mean #34 ?

**Comment by CookieNoob** [comment] 2017-01-19 13:41
xD yea, well 35 was the duplicate of 34...

**Closed** 2017-01-19 17:58 UTC
Labels: bug
